switches:
  - hostname: "DC1_SPINE_01"
    ip: "192.168.1.231" # Change this to your test switch IP
    username: "admin"
    password: "admin" # Change this to your credentials
    api_port: 443
    ssh_port: 22
  - hostname: "DC1_SPINE_02"
    ip: "192.168.1.229" # Change this to your test switch IP
    username: "admin"
    password: "admin" # Change this to your credentials
    api_port: 443
    ssh_port: 22
  - hostname: "DC1_LEAF_01"
    ip: "192.168.1.232" # Change this to your test switch IP
    username: "admin"
    password: "admin" # Change this to your credentials
    api_port: 443
    ssh_port: 22
  - hostname: "DC1_LEAF_02"
    ip: "192.168.1.230" # Change this to your test switch IP
    username: "admin"
    password: "admin" # Change this to your credentials
    api_port: 443
    ssh_port: 22
  - hostname: "DC1_LEAF_03"
    ip: "192.168.1.228" # Change this to your test switch IP
    username: "admin"
    password: "admin" # Change this to your credentials
    api_port: 443
    ssh_port: 22
